# Generated by Django 4.2.10 on 2024-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
