# Generated by Django 4.2.10 on 2024-08-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
