# Generated by Django 4.2.10 on 2024-08-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cost',
            new_name='price',
        ),
    ]
