# Generated by Django 4.2.10 on 2024-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
